Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: 'outputs/2025-09-11/18-12-31'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
